package com.charly.diqualifiers

const val DI_WEATHER_API_KEY = "DI_WEATHER_API_KEY"
const val DI_IS_DEBUG = "DI_IS_DEBUG"
const val DI_WEATHER_UNITS = "DI_WEATHER_UNITS"
const val DI_WEATHER_CACHE_TIME_IN_MILLIS = "DI_WEATHER_CACHE_TIME_IN_MILLIS"
